const CANVAS_WIDTH = 368;
// const CANVAS_WIDTH = 1024;
const CANVAS_HEIGHT = 576;
// const CANVAS_HEIGHT = 576;
const GRAVITY = 0.5;

const SPEED=5;

const INITIAL_Y_VELOCITY=-6;

const POINT=10;

export { CANVAS_HEIGHT,CANVAS_WIDTH, GRAVITY ,SPEED,INITIAL_Y_VELOCITY,POINT};
